### ISSUE TITLE
game_events#leave (Google::HTTPAuthorizationFailed) "Google::HTTPAuthorizationFailed"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#148]
<meta name="exception_notification_http">
<h2>Google::HTTPAuthorizationFailed occurred in game_events</h2>
<pre>
Google::HTTPAuthorizationFailed
lib/calendar.rb:81:in `new&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://dev-gamesocial.herokuapp.com/game_events/6/leave</td></tr>
<tr><td>IP address</td><td>72.182.2.187</td></tr>
<tr><td>Parameters</td><td>{&quot;controller&quot;=&gt;&quot;game_events&quot;, &quot;action&quot;=&gt;&quot;leave&quot;, &quot;id&quot;=&gt;&quot;6&quot;}</td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-01-06 07:04:46 -0600</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td>&quot;ae9e2f330f65510dda96374352fa726f&quot;</td></tr>
<tr><td>data</td><td>#&lt;ActionDispatch::Request::Session:0x007fb0936b9ba8 ...&gt;
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>HTTP_ACCEPT</td><td>text/html, application/xhtml+xml, application/xml</td></tr>
<tr><td>HTTP_ACCEPT_ENCODING</td><td>gzip, deflate, sdch</td></tr>
<tr><td>HTTP_ACCEPT_LANGUAGE</td><td>en-US,en;q=0.8</td></tr>
<tr><td>HTTP_CONNECTION</td><td>close</td></tr>
<tr><td>HTTP_CONNECT_TIME</td><td>1</td></tr>
<tr><td>HTTP_COOKIE</td><td>remember_token=VbIqQxqe5dbjMrYllvLemw; _GameSocial_session=QlJGaE1CTml4TEJJOU53SENUUEJXZlVUODVzem1wVnM0L21jRnR6ZG0ycDYvcEF3VEJRRHNGbjBhK2NVZG9oTG95eG54SEVxbHVFUUpoMDdVOGtmRHNBR0YzVlhBK3ZQVHVndFMzcUFKRGhQR05zZzFzb1ZIL3UyVjJvcC9yMFBrQVQwK0FJa0Z4Q3BQazFBa1EwYitHTVVyVXdMOXFkbkxqVGdmcnpoc1E3eE1SU0lXdGQ4am5aaUtvaWFQcUdSMTNtTFZSL3lKY3lrcTFRc2tWQ3d5cUl3ZThwZU5tVFY2eXpqamlIbzEyS2h5KzFQWWErU3NIRDNrdEMwdW9RVmRFbGp1Q1NFZWtBam1NbEdRNmlybmgyS2wybU1iOXBZTi9RM2g4QVFrR1E9LS0zZHNsMW5waDBUU0paQUphcW53SHl3PT0%3D--621b06b913bea02f961c0730bed19e9bf512ecbb</td></tr>
<tr><td>HTTP_HOST</td><td>dev-gamesocial.herokuapp.com</td></tr>
<tr><td>HTTP_REFERER</td><td>http://dev-gamesocial.herokuapp.com/game_events</td></tr>
<tr><td>HTTP_TOTAL_ROUTE_TIME</td><td>0</td></tr>
<tr><td>HTTP_USER_AGENT</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36</td></tr>
<tr><td>HTTP_VERSION</td><td>HTTP/1.1</td></tr>
<tr><td>HTTP_VIA</td><td>1.1 vegur</td></tr>
<tr><td>HTTP_X_FORWARDED_FOR</td><td>72.182.2.187</td></tr>
<tr><td>HTTP_X_FORWARDED_PORT</td><td>80</td></tr>
<tr><td>HTTP_X_FORWARDED_PROTO</td><td>http</td></tr>
<tr><td>HTTP_X_REQUEST_ID</td><td>7d7eae27-b4ff-474e-93aa-7322ea93409a</td></tr>
<tr><td>HTTP_X_REQUEST_START</td><td>1420549486205</td></tr>
<tr><td>HTTP_X_XHR_REFERER</td><td>http://dev-gamesocial.herokuapp.com/game_events</td></tr>
<tr><td>ORIGINAL_FULLPATH</td><td>/game_events/6/leave</td></tr>
<tr><td>ORIGINAL_SCRIPT_NAME</td><td></td></tr>
<tr><td>PATH_INFO</td><td>/game_events/6/leave</td></tr>
<tr><td>QUERY_STRING</td><td></td></tr>
<tr><td>REMOTE_ADDR</td><td>10.167.6.21</td></tr>
<tr><td>REQUEST_METHOD</td><td>GET</td></tr>
<tr><td>REQUEST_PATH</td><td>/game_events/6/leave</td></tr>
<tr><td>REQUEST_URI</td><td>/game_events/6/leave</td></tr>
<tr><td>ROUTES_70198169398520_SCRIPT_NAME</td><td></td></tr>
<tr><td>SCRIPT_NAME</td><td></td></tr>
<tr><td>SERVER_NAME</td><td>dev-gamesocial.herokuapp.com</td></tr>
<tr><td>SERVER_PORT</td><td>80</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>HTTP/1.1</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>Unicorn 4.8.3</td></tr>
<tr><td>action_controller.instance</td><td>game_events#leave</td></tr>
<tr><td>action_dispatch.backtrace_cleaner</td><td>#&lt;Rails::BacktraceCleaner:0x007fb093bdd710&gt;</td></tr>
<tr><td>action_dispatch.cookies</td><td>#&lt;ActionDispatch::Cookies::CookieJar:0x007fb0936ec1e8&gt;</td></tr>
<tr><td>action_dispatch.encrypted_cookie_salt</td><td>encrypted cookie</td></tr>
<tr><td>action_dispatch.encrypted_signed_cookie_salt</td><td>signed encrypted cookie</td></tr>
<tr><td>action_dispatch.http_auth_salt</td><td>http authentication</td></tr>
<tr><td>action_dispatch.key_generator</td><td>#&lt;ActiveSupport::CachingKeyGenerator:0x007fb093bf0090&gt;</td></tr>
<tr><td>action_dispatch.logger</td><td>#&lt;Logger:0x007fb090f2df80&gt;</td></tr>
<tr><td>action_dispatch.parameter_filter</td><td>[:password]</td></tr>
<tr><td>action_dispatch.redirect_filter</td><td>[]</td></tr>
<tr><td>action_dispatch.remote_ip</td><td>72.182.2.187</td></tr>
<tr><td>action_dispatch.request.accepts</td><td>[#&lt;Mime::Type:0x007fb08fa14928 @synonyms=[&quot;application/xhtml+xml&quot;], @symbol=:html, @string=&quot;text/html&quot;&gt;, #&lt;Mime::Type:0x007fb08fa180f0 @synonyms=[&quot;text/xml&quot;, &quot;application/x-xml&quot;], @symbol=:xml, @string=&quot;application/xml&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.content_type</td><td></td></tr>
<tr><td>action_dispatch.request.formats</td><td>[#&lt;Mime::Type:0x007fb08fa14928 @synonyms=[&quot;application/xhtml+xml&quot;], @symbol=:html, @string=&quot;text/html&quot;&gt;, #&lt;Mime::Type:0x007fb08fa180f0 @synonyms=[&quot;text/xml&quot;, &quot;application/x-xml&quot;], @symbol=:xml, @string=&quot;application/xml&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.parameters</td><td>{&quot;controller&quot;=&gt;&quot;game_events&quot;, &quot;action&quot;=&gt;&quot;leave&quot;, &quot;id&quot;=&gt;&quot;6&quot;}</td></tr>
<tr><td>action_dispatch.request.path_parameters</td><td>{:controller=&gt;&quot;game_events&quot;, :action=&gt;&quot;leave&quot;, :id=&gt;&quot;6&quot;}</td></tr>
<tr><td>action_dispatch.request.query_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.request_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.unsigned_session_cookie</td><td>{&quot;session_id&quot;=&gt;&quot;ae9e2f330f65510dda96374352fa726f&quot;, &quot;_csrf_token&quot;=&gt;&quot;CaJIdxx4Zqz+h8Tms0dyiN8Ry6bSobH2mCdKSJRPivQ=&quot;, &quot;flash&quot;=&gt;{&quot;discard&quot;=&gt;[:notice], &quot;flashes&quot;=&gt;{:notice=&gt;&quot;Refreshed Access Token.&quot;}}}</td></tr>
<tr><td>action_dispatch.request_id</td><td>7d7eae27-b4ff-474e-93aa-7322ea93409a</td></tr>
<tr><td>action_dispatch.routes</td><td>#&lt;ActionDispatch::Routing::RouteSet:0x007fb091e6d9f0&gt;</td></tr>
<tr><td>action_dispatch.secret_key_base</td><td>01c2fcf30be73aa2250d7267fb2d907f1b9cfb47c44c0af798bdf884093f09c6ec1a5dafd7988fdd09f87b1827cc038714dec16299c8c1f318c51269554bd1ac</td></tr>
<tr><td>action_dispatch.secret_token</td><td></td></tr>
<tr><td>action_dispatch.show_detailed_exceptions</td><td>false</td></tr>
<tr><td>action_dispatch.show_exceptions</td><td>true</td></tr>
<tr><td>action_dispatch.signed_cookie_salt</td><td>signed cookie</td></tr>
<tr><td>rack.errors</td><td>#&lt;IO:0x007fb08ea56158&gt;</td></tr>
<tr><td>rack.hijack</td><td>#&lt;Proc:0x007fb0936a87e0@/app/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.3/lib/unicorn/http_request.rb:111&gt;</td></tr>
<tr><td>rack.hijack?</td><td>true</td></tr>
<tr><td>rack.input</td><td>#&lt;StringIO:0x007fb08ec99050&gt;</td></tr>
<tr><td>rack.logger</td><td>#&lt;Logger:0x007fb08f022aa0&gt;</td></tr>
<tr><td>rack.multiprocess</td><td>true</td></tr>
<tr><td>rack.multithread</td><td>false</td></tr>
<tr><td>rack.request.cookie_hash</td><td>{&quot;remember_token&quot;=&gt;&quot;VbIqQxqe5dbjMrYllvLemw&quot;, &quot;_GameSocial_session&quot;=&gt;&quot;QlJGaE1CTml4TEJJOU53SENUUEJXZlVUODVzem1wVnM0L21jRnR6ZG0ycDYvcEF3VEJRRHNGbjBhK2NVZG9oTG95eG54SEVxbHVFUUpoMDdVOGtmRHNBR0YzVlhBK3ZQVHVndFMzcUFKRGhQR05zZzFzb1ZIL3UyVjJvcC9yMFBrQVQwK0FJa0Z4Q3BQazFBa1EwYitHTVVyVXdMOXFkbkxqVGdmcnpoc1E3eE1SU0lXdGQ4am5aaUtvaWFQcUdSMTNtTFZSL3lKY3lrcTFRc2tWQ3d5cUl3ZThwZU5tVFY2eXpqamlIbzEyS2h5KzFQWWErU3NIRDNrdEMwdW9RVmRFbGp1Q1NFZWtBam1NbEdRNmlybmgyS2wybU1iOXBZTi9RM2g4QVFrR1E9LS0zZHNsMW5waDBUU0paQUphcW53SHl3PT0=--621b06b913bea02f961c0730bed19e9bf512ecbb&quot;}</td></tr>
<tr><td>rack.request.cookie_string</td><td>remember_token=VbIqQxqe5dbjMrYllvLemw; _GameSocial_session=QlJGaE1CTml4TEJJOU53SENUUEJXZlVUODVzem1wVnM0L21jRnR6ZG0ycDYvcEF3VEJRRHNGbjBhK2NVZG9oTG95eG54SEVxbHVFUUpoMDdVOGtmRHNBR0YzVlhBK3ZQVHVndFMzcUFKRGhQR05zZzFzb1ZIL3UyVjJvcC9yMFBrQVQwK0FJa0Z4Q3BQazFBa1EwYitHTVVyVXdMOXFkbkxqVGdmcnpoc1E3eE1SU0lXdGQ4am5aaUtvaWFQcUdSMTNtTFZSL3lKY3lrcTFRc2tWQ3d5cUl3ZThwZU5tVFY2eXpqamlIbzEyS2h5KzFQWWErU3NIRDNrdEMwdW9RVmRFbGp1Q1NFZWtBam1NbEdRNmlybmgyS2wybU1iOXBZTi9RM2g4QVFrR1E9LS0zZHNsMW5waDBUU0paQUphcW53SHl3PT0%3D--621b06b913bea02f961c0730bed19e9bf512ecbb</td></tr>
<tr><td>rack.request.query_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_string</td><td></td></tr>
<tr><td>rack.run_once</td><td>false</td></tr>
<tr><td>rack.session</td><td>#&lt;ActionDispatch::Request::Session:0x007fb0936b9ba8&gt;</td></tr>
<tr><td>rack.session.options</td><td>#&lt;ActionDispatch::Request::Session::Options:0x007fb0936b9ae0&gt;</td></tr>
<tr><td>rack.url_scheme</td><td>http</td></tr>
<tr><td>rack.version</td><td>[1, 2]</td></tr>
<tr><td>Process</td><td>9</td></tr>
<tr><td>Server</td><td>feedc7d0-25c2-4411-83d8-ae3756d61336</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
lib/calendar.rb:81:in `new&#39;
lib/calendar.rb:81:in `initialize_calendar&#39;
lib/calendar.rb:76:in `calendar&#39;
lib/calendar.rb:61:in `event&#39;
app/models/game_event.rb:54:in `export_game_event&#39;
app/models/user.rb:170:in `leave_game_event&#39;
app/controllers/game_events_controller.rb:77:in `leave&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=8&above-color=red&below-color=gray&width=5&limits=0,8&d=1,8,0,0,0,0,1' alt='{"runtimeerror":["Jan 07",1,"Jan 08",8,"Jan 13",1]}' title='{"runtimeerror":["Jan 07",1,"Jan 08",8,"Jan 13",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Google::HTTPAuthorizationFailed occurred in game_events</h2>
<pre>
Google::HTTPAuthorizationFailed
lib/calendar.rb:80:in `new&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://dev-gamesocial.herokuapp.com/game_events/6/leave</td></tr>
<tr><td>IP address</td><td>72.182.2.187</td></tr>
<tr><td>Parameters</td><td>{&quot;controller&quot;=&gt;&quot;game_events&quot;, &quot;action&quot;=&gt;&quot;leave&quot;, &quot;id&quot;=&gt;&quot;6&quot;}</td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-01-12 20:44:24 -0600</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td>&quot;ae9e2f330f65510dda96374352fa726f&quot;</td></tr>
<tr><td>data</td><td>#&lt;ActionDispatch::Request::Session:0x007f7557e6e848 ...&gt;
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>HTTP_ACCEPT</td><td>text/html, application/xhtml+xml, application/xml</td></tr>
<tr><td>HTTP_ACCEPT_ENCODING</td><td>gzip, deflate, sdch</td></tr>
<tr><td>HTTP_ACCEPT_LANGUAGE</td><td>en-US,en;q=0.8</td></tr>
<tr><td>HTTP_CONNECTION</td><td>close</td></tr>
<tr><td>HTTP_CONNECT_TIME</td><td>1</td></tr>
<tr><td>HTTP_COOKIE</td><td>remember_token=VbIqQxqe5dbjMrYllvLemw; _GameSocial_session=M2xhSjFRSFJzTlduQjlReWk3bTh5N3JFdnJEdDZrVHg5eWd4cVpTcHBsUkxEYkdXd0FqRHhiR2diRlU0eTlyajFTdENORU0vSEZ3aGx4ZGJUSnVCUHV3ZW5Wd3pCQU9YTXlia3lXeVQyVlRJQ1IvOVVIZFNGK0txKy9QNS84UENPQm1kemR2QXZWZUU5clRLT0dGWmxEelo2RHpUN1pDMXFYamFZdDVUbGNFUXZOL2pWL05FdDJYS0N6ZGpXcEJtdVNpSllSeDdHUHdGVDZSbWU0Q1lLZW9mTDlEeGZSQWROVXdLd2xjdHlsSjZoNXlHWXhIZ2wranl1c0FDVWdDeEJLbUI4Wk9Ra29oYmsrOXVKNGhZMGc9PS0tbXEzbjE2WUdmVnZ1SzVKWnlHY3pYdz09--3efb767a076c73ab051eb4b76f204dd2c06371a1</td></tr>
<tr><td>HTTP_HOST</td><td>dev-gamesocial.herokuapp.com</td></tr>
<tr><td>HTTP_REFERER</td><td>http://dev-gamesocial.herokuapp.com/game_events</td></tr>
<tr><td>HTTP_TOTAL_ROUTE_TIME</td><td>0</td></tr>
<tr><td>HTTP_USER_AGENT</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36</td></tr>
<tr><td>HTTP_VERSION</td><td>HTTP/1.1</td></tr>
<tr><td>HTTP_VIA</td><td>1.1 vegur</td></tr>
<tr><td>HTTP_X_FORWARDED_FOR</td><td>72.182.2.187</td></tr>
<tr><td>HTTP_X_FORWARDED_PORT</td><td>80</td></tr>
<tr><td>HTTP_X_FORWARDED_PROTO</td><td>http</td></tr>
<tr><td>HTTP_X_REQUEST_ID</td><td>e7b817be-5749-4951-85bd-ae9b1fec55a2</td></tr>
<tr><td>HTTP_X_REQUEST_START</td><td>1421117063889</td></tr>
<tr><td>HTTP_X_XHR_REFERER</td><td>http://dev-gamesocial.herokuapp.com/game_events</td></tr>
<tr><td>ORIGINAL_FULLPATH</td><td>/game_events/6/leave</td></tr>
<tr><td>ORIGINAL_SCRIPT_NAME</td><td></td></tr>
<tr><td>PATH_INFO</td><td>/game_events/6/leave</td></tr>
<tr><td>QUERY_STRING</td><td></td></tr>
<tr><td>REMOTE_ADDR</td><td>10.38.131.237</td></tr>
<tr><td>REQUEST_METHOD</td><td>GET</td></tr>
<tr><td>REQUEST_PATH</td><td>/game_events/6/leave</td></tr>
<tr><td>REQUEST_URI</td><td>/game_events/6/leave</td></tr>
<tr><td>ROUTES_70070969029760_SCRIPT_NAME</td><td></td></tr>
<tr><td>SCRIPT_NAME</td><td></td></tr>
<tr><td>SERVER_NAME</td><td>dev-gamesocial.herokuapp.com</td></tr>
<tr><td>SERVER_PORT</td><td>80</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>HTTP/1.1</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>Unicorn 4.8.3</td></tr>
<tr><td>action_controller.instance</td><td>game_events#leave</td></tr>
<tr><td>action_dispatch.backtrace_cleaner</td><td>#&lt;Rails::BacktraceCleaner:0x007f755802bb18&gt;</td></tr>
<tr><td>action_dispatch.cookies</td><td>#&lt;ActionDispatch::Cookies::CookieJar:0x007f7557e9eb88&gt;</td></tr>
<tr><td>action_dispatch.encrypted_cookie_salt</td><td>encrypted cookie</td></tr>
<tr><td>action_dispatch.encrypted_signed_cookie_salt</td><td>signed encrypted cookie</td></tr>
<tr><td>action_dispatch.http_auth_salt</td><td>http authentication</td></tr>
<tr><td>action_dispatch.key_generator</td><td>#&lt;ActiveSupport::CachingKeyGenerator:0x007f7558036978&gt;</td></tr>
<tr><td>action_dispatch.logger</td><td>#&lt;Logger:0x007f7554881258&gt;</td></tr>
<tr><td>action_dispatch.parameter_filter</td><td>[:password]</td></tr>
<tr><td>action_dispatch.redirect_filter</td><td>[]</td></tr>
<tr><td>action_dispatch.remote_ip</td><td>72.182.2.187</td></tr>
<tr><td>action_dispatch.request.accepts</td><td>[#&lt;Mime::Type:0x007f7553e06c60 @synonyms=[&quot;application/xhtml+xml&quot;], @symbol=:html, @string=&quot;text/html&quot;&gt;, #&lt;Mime::Type:0x007f7553e0bf80 @synonyms=[&quot;text/xml&quot;, &quot;application/x-xml&quot;], @symbol=:xml, @string=&quot;application/xml&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.content_type</td><td></td></tr>
<tr><td>action_dispatch.request.formats</td><td>[#&lt;Mime::Type:0x007f7553e06c60 @synonyms=[&quot;application/xhtml+xml&quot;], @symbol=:html, @string=&quot;text/html&quot;&gt;, #&lt;Mime::Type:0x007f7553e0bf80 @synonyms=[&quot;text/xml&quot;, &quot;application/x-xml&quot;], @symbol=:xml, @string=&quot;application/xml&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.parameters</td><td>{&quot;controller&quot;=&gt;&quot;game_events&quot;, &quot;action&quot;=&gt;&quot;leave&quot;, &quot;id&quot;=&gt;&quot;6&quot;}</td></tr>
<tr><td>action_dispatch.request.path_parameters</td><td>{:controller=&gt;&quot;game_events&quot;, :action=&gt;&quot;leave&quot;, :id=&gt;&quot;6&quot;}</td></tr>
<tr><td>action_dispatch.request.query_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.request_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.unsigned_session_cookie</td><td>{&quot;session_id&quot;=&gt;&quot;ae9e2f330f65510dda96374352fa726f&quot;, &quot;_csrf_token&quot;=&gt;&quot;CaJIdxx4Zqz+h8Tms0dyiN8Ry6bSobH2mCdKSJRPivQ=&quot;, &quot;flash&quot;=&gt;{&quot;discard&quot;=&gt;[:notice], &quot;flashes&quot;=&gt;{:notice=&gt;&quot;Signed in.&quot;}}}</td></tr>
<tr><td>action_dispatch.request_id</td><td>e7b817be-5749-4951-85bd-ae9b1fec55a2</td></tr>
<tr><td>action_dispatch.routes</td><td>#&lt;ActionDispatch::Routing::RouteSet:0x007f75566fa900&gt;</td></tr>
<tr><td>action_dispatch.secret_key_base</td><td>01c2fcf30be73aa2250d7267fb2d907f1b9cfb47c44c0af798bdf884093f09c6ec1a5dafd7988fdd09f87b1827cc038714dec16299c8c1f318c51269554bd1ac</td></tr>
<tr><td>action_dispatch.secret_token</td><td></td></tr>
<tr><td>action_dispatch.show_detailed_exceptions</td><td>false</td></tr>
<tr><td>action_dispatch.show_exceptions</td><td>true</td></tr>
<tr><td>action_dispatch.signed_cookie_salt</td><td>signed cookie</td></tr>
<tr><td>rack.errors</td><td>#&lt;IO:0x007f7552e42158&gt;</td></tr>
<tr><td>rack.hijack</td><td>#&lt;Proc:0x007f7557e6d218@/app/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.3/lib/unicorn/http_request.rb:111&gt;</td></tr>
<tr><td>rack.hijack?</td><td>true</td></tr>
<tr><td>rack.input</td><td>#&lt;StringIO:0x007f7553049910&gt;</td></tr>
<tr><td>rack.logger</td><td>#&lt;Logger:0x007f7553466ae8&gt;</td></tr>
<tr><td>rack.multiprocess</td><td>true</td></tr>
<tr><td>rack.multithread</td><td>false</td></tr>
<tr><td>rack.request.cookie_hash</td><td>{&quot;remember_token&quot;=&gt;&quot;VbIqQxqe5dbjMrYllvLemw&quot;, &quot;_GameSocial_session&quot;=&gt;&quot;M2xhSjFRSFJzTlduQjlReWk3bTh5N3JFdnJEdDZrVHg5eWd4cVpTcHBsUkxEYkdXd0FqRHhiR2diRlU0eTlyajFTdENORU0vSEZ3aGx4ZGJUSnVCUHV3ZW5Wd3pCQU9YTXlia3lXeVQyVlRJQ1IvOVVIZFNGK0txKy9QNS84UENPQm1kemR2QXZWZUU5clRLT0dGWmxEelo2RHpUN1pDMXFYamFZdDVUbGNFUXZOL2pWL05FdDJYS0N6ZGpXcEJtdVNpSllSeDdHUHdGVDZSbWU0Q1lLZW9mTDlEeGZSQWROVXdLd2xjdHlsSjZoNXlHWXhIZ2wranl1c0FDVWdDeEJLbUI4Wk9Ra29oYmsrOXVKNGhZMGc9PS0tbXEzbjE2WUdmVnZ1SzVKWnlHY3pYdz09--3efb767a076c73ab051eb4b76f204dd2c06371a1&quot;}</td></tr>
<tr><td>rack.request.cookie_string</td><td>remember_token=VbIqQxqe5dbjMrYllvLemw; _GameSocial_session=M2xhSjFRSFJzTlduQjlReWk3bTh5N3JFdnJEdDZrVHg5eWd4cVpTcHBsUkxEYkdXd0FqRHhiR2diRlU0eTlyajFTdENORU0vSEZ3aGx4ZGJUSnVCUHV3ZW5Wd3pCQU9YTXlia3lXeVQyVlRJQ1IvOVVIZFNGK0txKy9QNS84UENPQm1kemR2QXZWZUU5clRLT0dGWmxEelo2RHpUN1pDMXFYamFZdDVUbGNFUXZOL2pWL05FdDJYS0N6ZGpXcEJtdVNpSllSeDdHUHdGVDZSbWU0Q1lLZW9mTDlEeGZSQWROVXdLd2xjdHlsSjZoNXlHWXhIZ2wranl1c0FDVWdDeEJLbUI4Wk9Ra29oYmsrOXVKNGhZMGc9PS0tbXEzbjE2WUdmVnZ1SzVKWnlHY3pYdz09--3efb767a076c73ab051eb4b76f204dd2c06371a1</td></tr>
<tr><td>rack.request.query_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_string</td><td></td></tr>
<tr><td>rack.run_once</td><td>false</td></tr>
<tr><td>rack.session</td><td>#&lt;ActionDispatch::Request::Session:0x007f7557e6e848&gt;</td></tr>
<tr><td>rack.session.options</td><td>#&lt;ActionDispatch::Request::Session::Options:0x007f7557e6e708&gt;</td></tr>
<tr><td>rack.url_scheme</td><td>http</td></tr>
<tr><td>rack.version</td><td>[1, 2]</td></tr>
<tr><td>Process</td><td>6</td></tr>
<tr><td>Server</td><td>7c77a97a-2d0a-454d-9390-b8a80d280afc</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
lib/calendar.rb:80:in `new&#39;
lib/calendar.rb:80:in `initialize_calendar&#39;
lib/calendar.rb:76:in `calendar&#39;
lib/calendar.rb:61:in `event&#39;
app/models/game_event.rb:54:in `export_game_event&#39;
app/models/user.rb:170:in `leave_game_event&#39;
app/controllers/game_events_controller.rb:77:in `leave&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Jan 13",1]}' title='{"runtimeerror":["Jan 13",1]}'/>
