### ISSUE TITLE
# (RuntimeError) "can't add a new key into hash during iteration"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#177]
<meta name="exception_notification_http">
<h2>RuntimeError occurred in </h2>
<pre>
can&#39;t add a new key into hash during iteration
app/providers/steam_provider.rb:7:in `initialize&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-05-24 22:54:55 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[160]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1432526064.0986695</td></tr>
<tr><td>error_class</td><td>RuntimeError</td></tr>
<tr><td>error_message</td><td>can&#39;t add a new key into hash during iteration</td></tr>
<tr><td>failed_at</td><td>1432526094.6862886</td></tr>
<tr><td>jid</td><td>6e31abd00f4e410382d45c96</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>01ee922a-c981-47ce-bf36-27dddf966ce5</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:7:in `initialize&#39;
lib/workers/location_sync_worker.rb:12:in `new&#39;
lib/workers/location_sync_worker.rb:12:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Jul 01",1,"Aug 05",1]}' title='{"runtimeerror":["Jul 01",1,"Aug 05",1]}'/>

**Comment by bfosberry** [comment]
Can't replicate :(

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>RuntimeError occurred in </h2>
<pre>
can&#39;t add a new key into hash during iteration
app/providers/steam_provider.rb:7:in `initialize&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-05-30 07:58:13 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[289]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1432976070.6295936</td></tr>
<tr><td>error_class</td><td>RuntimeError</td></tr>
<tr><td>error_message</td><td>can&#39;t add a new key into hash during iteration</td></tr>
<tr><td>failed_at</td><td>1432990693.264228</td></tr>
<tr><td>jid</td><td>74c597807243b1541ae323ea</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>00ba3039-4d43-47b1-8f0f-84a09d7f9051</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:7:in `initialize&#39;
lib/workers/location_sync_worker.rb:12:in `new&#39;
lib/workers/location_sync_worker.rb:12:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["May 30",1]}' title='{"runtimeerror":["May 30",1]}'/>

**Comment by bfosberry** [comment]
Looks like a steam condenser issue, killing for now

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>RuntimeError occurred in </h2>
<pre>
can&#39;t add a new key into hash during iteration
app/providers/steam_provider.rb:7:in `initialize&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-08-18 06:09:47 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[145]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1439896157.717217</td></tr>
<tr><td>error_class</td><td>RuntimeError</td></tr>
<tr><td>error_message</td><td>can&#39;t add a new key into hash during iteration</td></tr>
<tr><td>failed_at</td><td>1439896187.5750592</td></tr>
<tr><td>jid</td><td>3de4581d0948f3a6473e9be0</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>c6d08a3f-abac-4fa0-b474-14c03b18ca2b</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:7:in `initialize&#39;
lib/workers/location_sync_worker.rb:12:in `new&#39;
lib/workers/location_sync_worker.rb:12:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Aug 18",1]}' title='{"runtimeerror":["Aug 18",1]}'/>

**Comment by bfosberry** [comment]
Updated steam condenser, hopefully this was fixed

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>RuntimeError occurred in </h2>
<pre>
can&#39;t add a new key into hash during iteration
app/providers/steam_provider.rb:7:in `initialize&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-09 11:05:11 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[171]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1441814674.0607665</td></tr>
<tr><td>error_class</td><td>RuntimeError</td></tr>
<tr><td>error_message</td><td>can&#39;t add a new key into hash during iteration</td></tr>
<tr><td>failed_at</td><td>1441814711.6945229</td></tr>
<tr><td>jid</td><td>06d15fe16b2df104146b2871</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>e484c3ae-febb-4a96-9f9a-65a54eb27ebd</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:7:in `initialize&#39;
lib/workers/location_sync_worker.rb:14:in `new&#39;
lib/workers/location_sync_worker.rb:14:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 09",1]}' title='{"runtimeerror":["Sep 09",1]}'/>
