### ISSUE TITLE
# (SignalException) "SIGTERM"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#190]
<meta name="exception_notification_http">
<h2>SignalException occurred in </h2>
<pre>
SIGTERM
lib/tasks/sync.rake:12:in `block (3 levels) in &lt;top (required)&gt;&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-06-26 08:59:32 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>action</td><td></td></tr>
<tr><td>component</td><td></td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>rake_env</td><td></td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>ed9e00a5-00c6-46f9-8107-a0b46468a4fa</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
lib/tasks/sync.rake:12:in `block (3 levels) in &lt;top (required)&gt;&#39;
lib/tasks/sync.rake:11:in `block (2 levels) in &lt;top (required)&gt;&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Aug 05",1]}' title='{"runtimeerror":["Aug 05",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>SignalException occurred in </h2>
<pre>
SIGTERM
app/models/alert.rb:3:in `&lt;class:Alert&gt;&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-08-16 14:24:20 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>action</td><td></td></tr>
<tr><td>component</td><td></td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>rake_env</td><td></td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>e0f06457-e6fd-4355-b9be-5426b8e0ac7f</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/models/alert.rb:3:in `&lt;class:Alert&gt;&#39;
app/models/alert.rb:2:in `&lt;top (required)&gt;&#39;
config/environment.rb:5:in `&lt;top (required)&gt;&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Aug 16",1]}' title='{"runtimeerror":["Aug 16",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>SignalException occurred in </h2>
<pre>
SIGTERM
lib/tasks/sync.rake:11:in `block (2 levels) in &lt;top (required)&gt;&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-08-25 04:04:24 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>action</td><td></td></tr>
<tr><td>component</td><td></td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>rake_env</td><td></td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>203c5896-451c-452e-be17-5bf698f5fa2a</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
lib/tasks/sync.rake:11:in `block (2 levels) in &lt;top (required)&gt;&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Aug 25",1]}' title='{"runtimeerror":["Aug 25",1]}'/>
