### ISSUE TITLE
# (NoMethodError) "undefined method `name' for nil:NilClass"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#209]
<meta name="exception_notification_http">
<h2>NoMethodError occurred in </h2>
<pre>
undefined method `name&#39; for nil:NilClass
app/importers/steam_importer.rb:39:in `block in import_friends&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-08-19 11:59:11 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[1]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1439989229.0441146</td></tr>
<tr><td>error_class</td><td>NoMethodError</td></tr>
<tr><td>error_message</td><td>undefined method `name&#39; for nil:NilClass</td></tr>
<tr><td>failed_at</td><td>1440003551.676061</td></tr>
<tr><td>jid</td><td>37e0955a5a3fff7ce0d841f9</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>24671d4c-16b2-4033-80da-68bebf8247c3</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/importers/steam_importer.rb:39:in `block in import_friends&#39;
app/importers/steam_importer.rb:35:in `each&#39;
app/importers/steam_importer.rb:35:in `import_friends&#39;
lib/workers/sync_worker.rb:17:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=6&above-color=red&below-color=gray&width=5&limits=0,6&d=6,6,6,6,5,5,1' alt='{"runtimeerror":["Aug 29",6,"Aug 30",6,"Aug 31",6,"Sep 01",6,"Sep 02",5,"Sep 03",5,"Sep 04",1]}' title='{"runtimeerror":["Aug 29",6,"Aug 30",6,"Aug 31",6,"Sep 01",6,"Sep 02",5,"Sep 03",5,"Sep 04",1]}'/>

**Comment by bfosberry** [comment]
hmm..cant replicate

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>NoMethodError occurred in </h2>
<pre>
undefined method `name&#39; for nil:NilClass
app/importers/steam_importer.rb:39:in `block in import_friends&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-02 08:01:55 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[88]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1441198821.9152343</td></tr>
<tr><td>error_class</td><td>NoMethodError</td></tr>
<tr><td>error_message</td><td>undefined method `name&#39; for nil:NilClass</td></tr>
<tr><td>failed_at</td><td>1441198914.368524</td></tr>
<tr><td>jid</td><td>96734bed549e1dd424f3aa72</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>42fe32f9-5099-47f9-bc07-9f867b587f58</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/importers/steam_importer.rb:39:in `block in import_friends&#39;
app/importers/steam_importer.rb:35:in `each&#39;
app/importers/steam_importer.rb:35:in `import_friends&#39;
lib/workers/sync_worker.rb:18:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 02",1]}' title='{"runtimeerror":["Sep 02",1]}'/>

**Comment by bfosberry** [comment]
:( cant replicate

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>NoMethodError occurred in </h2>
<pre>
undefined method `name&#39; for nil:NilClass
app/importers/steam_importer.rb:39:in `block in import_friends&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-03 08:03:21 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[88]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1441285246.588722</td></tr>
<tr><td>error_class</td><td>NoMethodError</td></tr>
<tr><td>error_message</td><td>undefined method `name&#39; for nil:NilClass</td></tr>
<tr><td>failed_at</td><td>1441285401.5126476</td></tr>
<tr><td>jid</td><td>ab3625f495805ec16f20838b</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>dc762a6f-ef81-47b3-914f-e23cadae673f</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/importers/steam_importer.rb:39:in `block in import_friends&#39;
app/importers/steam_importer.rb:35:in `each&#39;
app/importers/steam_importer.rb:35:in `import_friends&#39;
lib/workers/sync_worker.rb:18:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 03",1]}' title='{"runtimeerror":["Sep 03",1]}'/>

**Comment by bfosberry** [comment]
Updated rails version, should be fixed
