### ISSUE TITLE
# (SteamCondenser::Error) "XML data could not be parsed: {N} Service Unavailable"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#229]
<meta name="exception_notification_http">
<h2>SteamCondenser::Error occurred in </h2>
<pre>
XML data could not be parsed: 503 Service Unavailable
app/providers/steam_provider.rb:7:in `initialize&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-04 08:08:42 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[70]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1441371652.4979117</td></tr>
<tr><td>error_class</td><td>SteamCondenser::Error</td></tr>
<tr><td>error_message</td><td>XML data could not be parsed: 503 Service Unavailable</td></tr>
<tr><td>failed_at</td><td>1441372122.9536717</td></tr>
<tr><td>jid</td><td>6c986a0727dd5edf8196912e</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>965f8356-a8f4-4026-992c-3c368114935f</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:7:in `initialize&#39;
lib/workers/sync_worker.rb:13:in `new&#39;
lib/workers/sync_worker.rb:13:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=7&above-color=red&below-color=gray&width=5&limits=0,7&d=0,0,0,0,0,0,7' alt='{"runtimeerror":["Sep 04",7]}' title='{"runtimeerror":["Sep 04",7]}'/>

**Comment by bfosberry** [comment]
Needs a retry
