### ISSUE TITLE
# (NoMethodError) "undefined method `size=' for [\"{N}.{N}\", \"{N}\"]:Array"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#250]
<meta name="exception_notification_http">
<h2>NoMethodError occurred in </h2>
<pre>
undefined method `size=&#39; for [&quot;199.96.83.34&quot;, &quot;27016&quot;]:Array
app/models/user.rb:140:in `set_game&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-09 21:54:25 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[46]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1441853355.2030954</td></tr>
<tr><td>error_class</td><td>NoMethodError</td></tr>
<tr><td>error_message</td><td>undefined method `size=&#39; for [&quot;199.96.83.34&quot;, &quot;27016&quot;]:Array</td></tr>
<tr><td>failed_at</td><td>1441853665.3578517</td></tr>
<tr><td>jid</td><td>69763929f39406b747eaba00</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>070e6338-a9e8-473a-8d2b-3e97d2ec6c72</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/models/user.rb:140:in `set_game&#39;
app/importers/steam_importer.rb:74:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=64&above-color=red&below-color=gray&width=5&limits=0,64&d=0,0,0,0,0,0,64' alt='{"runtimeerror":["Sep 10",64]}' title='{"runtimeerror":["Sep 10",64]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>NoMethodError occurred in </h2>
<pre>
undefined method `size=&#39; for [&quot;199.96.83.34&quot;, &quot;27016&quot;]:Array
app/models/user.rb:141:in `set_game&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-09 22:21:27 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[46]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1441854861.0405436</td></tr>
<tr><td>error_class</td><td>NoMethodError</td></tr>
<tr><td>error_message</td><td>undefined method `size=&#39; for [&quot;199.96.83.34&quot;, &quot;27016&quot;]:Array</td></tr>
<tr><td>failed_at</td><td>1441855174.2556453</td></tr>
<tr><td>jid</td><td>ee197403ad2e941a0593cb00</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retried_at</td><td>1441855287.5102832</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>2</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>5544c797-9af3-43fb-988e-cb59e69a0002</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/models/user.rb:141:in `set_game&#39;
app/importers/steam_importer.rb:74:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 10",1]}' title='{"runtimeerror":["Sep 10",1]}'/>
