### ISSUE TITLE
# (Errno::ETIMEDOUT) "Connection timed out - connect({N}) for \"api.steampowered.com\" port {N}"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#259]
<meta name="exception_notification_http">
<h2>Errno::ETIMEDOUT occurred in </h2>
<pre>
Connection timed out - connect(2) for &quot;api.steampowered.com&quot; port 443
app/providers/steam_provider.rb:54:in `block in summary&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-11 12:37:10 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[200]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1441992882.8297162</td></tr>
<tr><td>error_class</td><td>Errno::ETIMEDOUT</td></tr>
<tr><td>error_message</td><td>Connection timed out - connect(2) for &quot;api.steampowered.com&quot; port 443</td></tr>
<tr><td>failed_at</td><td>1441993030.4030266</td></tr>
<tr><td>jid</td><td>5405d43ff18d99cbcfd2f318</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>7bad395c-694b-41d9-93c8-9f99e608fa47</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:54:in `block in summary&#39;
app/providers/steam_provider.rb:53:in `summary&#39;
app/providers/steam_provider.rb:45:in `current_game&#39;
app/importers/steam_importer.rb:72:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=5&above-color=red&below-color=gray&width=5&limits=0,5&d=0,0,0,0,0,0,5' alt='{"runtimeerror":["Sep 11",5]}' title='{"runtimeerror":["Sep 11",5]}'/>

**Comment by bfosberry** [comment]
needs retry
