### ISSUE TITLE
# (EOFError) "end of file reached"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#269]
<meta name="exception_notification_http">
<h2>EOFError occurred in </h2>
<pre>
end of file reached
app/providers/steam_provider.rb:54:in `block in summary&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-14 09:33:09 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[92]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1442240975.5162606</td></tr>
<tr><td>error_class</td><td>EOFError</td></tr>
<tr><td>error_message</td><td>end of file reached</td></tr>
<tr><td>failed_at</td><td>1442241052.7416902</td></tr>
<tr><td>jid</td><td>5e9e07759678daf5d9315533</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>fe9fd312-f28c-4cf0-a8d5-ea1028ca0766</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:54:in `block in summary&#39;
app/providers/steam_provider.rb:53:in `summary&#39;
app/providers/steam_provider.rb:45:in `current_game&#39;
app/importers/steam_importer.rb:72:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 14",1]}' title='{"runtimeerror":["Sep 14",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>EOFError occurred in </h2>
<pre>
end of file reached
app/providers/steam_provider.rb:76:in `block in summary&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-30 00:31:43 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[222]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>created_at</td><td>1443590669.23888</td></tr>
<tr><td>enqueued_at</td><td>1443590972.7697165</td></tr>
<tr><td>error_class</td><td>EOFError</td></tr>
<tr><td>error_message</td><td>end of file reached</td></tr>
<tr><td>failed_at</td><td>1443591103.1932082</td></tr>
<tr><td>jid</td><td>4a96807e0a1656938c12276e</td></tr>
<tr><td>queue</td><td>sync_location</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>4fc27502-2105-4d11-8ed3-0a1214ab8423</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:76:in `block in summary&#39;
app/providers/steam_provider.rb:75:in `summary&#39;
app/providers/steam_provider.rb:67:in `current_game&#39;
app/importers/steam_importer.rb:114:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 30",1]}' title='{"runtimeerror":["Sep 30",1]}'/>
