### ISSUE TITLE
# (NoMethodError) "undefined method `each' for nil:NilClass"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#271]
<meta name="exception_notification_http">
<h2>NoMethodError occurred in </h2>
<pre>
undefined method `each&#39; for nil:NilClass
app/providers/steam_provider.rb:20:in `block in games&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-15 08:02:56 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[65]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1442322043.8468146</td></tr>
<tr><td>error_class</td><td>NoMethodError</td></tr>
<tr><td>error_message</td><td>undefined method `each&#39; for nil:NilClass</td></tr>
<tr><td>failed_at</td><td>1442322176.7877681</td></tr>
<tr><td>jid</td><td>26433beb2bceabb28db31176</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>a580f64e-e696-41bd-9eea-95376065eefc</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:20:in `block in games&#39;
app/providers/steam_provider.rb:19:in `games&#39;
app/importers/steam_importer.rb:12:in `import_games&#39;
lib/workers/sync_worker.rb:17:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=238&above-color=red&below-color=gray&width=5&limits=0,238&d=19,57,58,58,57,56,238' alt='{"runtimeerror":["Sep 21",19,"Sep 22",57,"Sep 23",58,"Sep 24",58,"Sep 25",57,"Sep 26",56,"Sep 27",238]}' title='{"runtimeerror":["Sep 21",19,"Sep 22",57,"Sep 23",58,"Sep 24",58,"Sep 25",57,"Sep 26",56,"Sep 27",238]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>NoMethodError occurred in </h2>
<pre>
undefined method `each&#39; for nil:NilClass
app/providers/steam_provider.rb:20:in `block in games&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-26 08:01:54 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[65]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1443272443.0970101</td></tr>
<tr><td>error_class</td><td>NoMethodError</td></tr>
<tr><td>error_message</td><td>undefined method `each&#39; for nil:NilClass</td></tr>
<tr><td>failed_at</td><td>1443272514.2639132</td></tr>
<tr><td>jid</td><td>3b39c626dca719a7cb8bc05d</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>959a0d45-27ec-4dd6-89e5-4ffbba6550e6</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:20:in `block in games&#39;
app/providers/steam_provider.rb:19:in `games&#39;
app/importers/steam_importer.rb:12:in `import_games&#39;
lib/workers/sync_worker.rb:17:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 26",1]}' title='{"runtimeerror":["Sep 26",1]}'/>
