### ISSUE TITLE
# (SteamCondenser::Error::WebApi) "Your Web API request has been rejected. You most likely did not specify a valid Web API key."

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#272]
<meta name="exception_notification_http">
<h2>SteamCondenser::Error::WebApi occurred in </h2>
<pre>
Your Web API request has been rejected. You most likely did not specify a valid Web API key.
app/providers/steam_provider.rb:26:in `block in friends&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-15 08:10:05 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[248]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1442322044.044459</td></tr>
<tr><td>error_class</td><td>SteamCondenser::Error::WebApi</td></tr>
<tr><td>error_message</td><td>Your Web API request has been rejected. You most likely did not specify a valid Web API key.</td></tr>
<tr><td>failed_at</td><td>1442322409.3818998</td></tr>
<tr><td>jid</td><td>0f51b76d7b4a8f9c9a0b06e6</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retried_at</td><td>1442322605.1706667</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>1</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>a580f64e-e696-41bd-9eea-95376065eefc</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:26:in `block in friends&#39;
app/providers/steam_provider.rb:25:in `friends&#39;
app/importers/steam_importer.rb:32:in `import_friends&#39;
lib/workers/sync_worker.rb:19:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=3&above-color=red&below-color=gray&width=5&limits=0,3&d=2,2,3,2,2,2,2' alt='{"runtimeerror":["Sep 19",2,"Sep 20",2,"Sep 21",3,"Sep 22",2,"Sep 23",2,"Sep 24",2,"Sep 25",2]}' title='{"runtimeerror":["Sep 19",2,"Sep 20",2,"Sep 21",3,"Sep 22",2,"Sep 23",2,"Sep 24",2,"Sep 25",2]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>SteamCondenser::Error::WebApi occurred in </h2>
<pre>
Your Web API request has been rejected. You most likely did not specify a valid Web API key.
app/providers/steam_provider.rb:26:in `block in friends&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-26 08:10:21 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[248]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1443272443.3481922</td></tr>
<tr><td>error_class</td><td>SteamCondenser::Error::WebApi</td></tr>
<tr><td>error_message</td><td>Your Web API request has been rejected. You most likely did not specify a valid Web API key.</td></tr>
<tr><td>failed_at</td><td>1443272787.9777644</td></tr>
<tr><td>jid</td><td>204c5cac9a24be5639f0459c</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retried_at</td><td>1443273021.2460556</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>1</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>959a0d45-27ec-4dd6-89e5-4ffbba6550e6</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:26:in `block in friends&#39;
app/providers/steam_provider.rb:25:in `friends&#39;
app/importers/steam_importer.rb:32:in `import_friends&#39;
lib/workers/sync_worker.rb:19:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 26",1]}' title='{"runtimeerror":["Sep 26",1]}'/>
