### ISSUE TITLE
# (Errno::ENOENT) "No such file or directory @ rb_sysopen - /app/tmp/cache/A{N}/{N}/.permissions_check.{N}.{N}"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#273]
<meta name="exception_notification_http">
<h2>Errno::ENOENT occurred in </h2>
<pre>
No such file or directory @ rb_sysopen - /app/tmp/cache/A67/870/.permissions_check.69876881931580.3.159074
app/providers/steam_provider.rb:71:in `summary&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-15 13:45:13 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[192]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1442342673.833055</td></tr>
<tr><td>error_class</td><td>Errno::ENOENT</td></tr>
<tr><td>error_message</td><td>No such file or directory @ rb_sysopen - /app/tmp/cache/A67/870/.permissions_check.69876881931580.3.159074</td></tr>
<tr><td>failed_at</td><td>1442342713.6927185</td></tr>
<tr><td>jid</td><td>d8a08d0126b4cf64277e2efc</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>a580f64e-e696-41bd-9eea-95376065eefc</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:71:in `summary&#39;
app/providers/steam_provider.rb:63:in `current_game&#39;
app/importers/steam_importer.rb:94:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=2&above-color=red&below-color=gray&width=5&limits=0,2&d=0,0,0,0,1,0,2' alt='{"runtimeerror":["Sep 15",1,"Sep 17",2]}' title='{"runtimeerror":["Sep 15",1,"Sep 17",2]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Errno::ENOENT occurred in </h2>
<pre>
No such file or directory @ rb_sysopen - /app/tmp/cache/A67/870/.permissions_check.70339209882320.3.786841
app/providers/steam_provider.rb:71:in `summary&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-26 02:10:22 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[192]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1443251079.5929146</td></tr>
<tr><td>error_class</td><td>Errno::ENOENT</td></tr>
<tr><td>error_message</td><td>No such file or directory @ rb_sysopen - /app/tmp/cache/A67/870/.permissions_check.70339209882320.3.786841</td></tr>
<tr><td>failed_at</td><td>1443251421.9663374</td></tr>
<tr><td>jid</td><td>27bf76631b5be49128e58e0d</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>959a0d45-27ec-4dd6-89e5-4ffbba6550e6</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:71:in `summary&#39;
app/providers/steam_provider.rb:63:in `current_game&#39;
app/importers/steam_importer.rb:94:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 26",1]}' title='{"runtimeerror":["Sep 26",1]}'/>
