### ISSUE TITLE
# (SteamCondenser::Error) "The specified profile could not be found."

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#277]
<meta name="exception_notification_http">
<h2>SteamCondenser::Error occurred in </h2>
<pre>
The specified profile could not be found.
app/importers/steam_importer.rb:67:in `create_user_from_friend&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-26 08:02:13 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[61]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1443272443.0992706</td></tr>
<tr><td>error_class</td><td>SteamCondenser::Error</td></tr>
<tr><td>error_message</td><td>The specified profile could not be found.</td></tr>
<tr><td>failed_at</td><td>1443272533.6596289</td></tr>
<tr><td>jid</td><td>8cd4140f0fcf1794f8fcf3c9</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>959a0d45-27ec-4dd6-89e5-4ffbba6550e6</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/importers/steam_importer.rb:67:in `create_user_from_friend&#39;
app/importers/steam_importer.rb:33:in `block in import_friends&#39;
app/importers/steam_importer.rb:32:in `each&#39;
app/importers/steam_importer.rb:32:in `import_friends&#39;
lib/workers/sync_worker.rb:19:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=136&above-color=red&below-color=gray&width=5&limits=0,136&d=0,0,12,26,3,136,13' alt='{"runtimeerror":["Sep 26",12,"Sep 27",26,"Sep 28",3,"Sep 29",136,"Sep 30",13]}' title='{"runtimeerror":["Sep 26",12,"Sep 27",26,"Sep 28",3,"Sep 29",136,"Sep 30",13]}'/>

**Comment by bfosberry** [comment]
Needs to be supressed and ignored
