### ISSUE TITLE
# (Redis::CommandError) "OOM command not allowed when used memory > 'maxmemory'."

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#283]
<meta name="exception_notification_http">
<h2>Redis::CommandError occurred in </h2>
<pre>
OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.
app/providers/steam_provider.rb:25:in `friends&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-26 19:04:14 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[1]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1443312054.8810885</td></tr>
<tr><td>error_class</td><td>Redis::CommandError</td></tr>
<tr><td>error_message</td><td>OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.</td></tr>
<tr><td>failed_at</td><td>1443312254.7274923</td></tr>
<tr><td>jid</td><td>899fdf262260ca13ba8742cd</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>ec53abec-e2a8-470f-82de-439d3bb16f00</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:25:in `friends&#39;
app/importers/steam_importer.rb:32:in `import_friends&#39;
lib/workers/sync_worker.rb:19:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=29&above-color=red&below-color=gray&width=5&limits=0,29&d=0,1,0,9,2,0,29' alt='{"runtimeerror":["Oct 18",1,"Oct 20",9,"Oct 21",2,"Oct 23",29]}' title='{"runtimeerror":["Oct 18",1,"Oct 20",9,"Oct 21",2,"Oct 23",29]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Redis::CommandError occurred in </h2>
<pre>
OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.
app/providers/steam_provider.rb:25:in `friends&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-27 16:28:12 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[1]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>created_at</td><td>1443389135.1342993</td></tr>
<tr><td>enqueued_at</td><td>1443389135.1343267</td></tr>
<tr><td>error_class</td><td>Redis::CommandError</td></tr>
<tr><td>error_message</td><td>OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.</td></tr>
<tr><td>failed_at</td><td>1443389292.2317336</td></tr>
<tr><td>jid</td><td>46c730b2ef422e725b27295f</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>6d0d38ab-3dbd-4bad-978d-90b257206f2e</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:25:in `friends&#39;
app/importers/steam_importer.rb:32:in `import_friends&#39;
lib/workers/sync_worker.rb:19:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 27",1]}' title='{"runtimeerror":["Sep 27",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Redis::CommandError occurred in </h2>
<pre>
OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.

</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-29 20:32:59 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[346]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>created_at</td><td>1443559467.656899</td></tr>
<tr><td>enqueued_at</td><td>1443560008.8241131</td></tr>
<tr><td>error_class</td><td>ActiveRecord::StatementInvalid</td></tr>
<tr><td>error_message</td><td>PG::ConnectionBad: PQsocket() can&#39;t get socket descriptor: SET client_min_messages TO &#39;warning&#39;</td></tr>
<tr><td>failed_at</td><td>1443576749.1908784</td></tr>
<tr><td>jid</td><td>6310be64cedf30ea79204812</td></tr>
<tr><td>queue</td><td>sync_location</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>9c720ed6-8ffb-49e6-bb86-23a419c48734</td></tr>
</table>
<h2>Backtrace</h2>
<pre>

</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=2&above-color=red&below-color=gray&width=5&limits=0,2&d=0,0,0,0,0,0,2' alt='{"runtimeerror":["Sep 30",2]}' title='{"runtimeerror":["Sep 30",2]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Redis::CommandError occurred in </h2>
<pre>
OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.

</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-29 21:20:32 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[5]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>created_at</td><td>1443569978.346962</td></tr>
<tr><td>enqueued_at</td><td>1443578861.753719</td></tr>
<tr><td>error_class</td><td>PG::ConnectionBad</td></tr>
<tr><td>error_message</td><td>could not connect to server: Connection refused
	Is the server running on host &quot;postgres-e045225b-1.bfosberry.cont.tutum.io&quot; (104.236.89.117) and accepting
	TCP/IP connections on port 49155?
</td></tr>
<tr><td>failed_at</td><td>1443578765.6990018</td></tr>
<tr><td>jid</td><td>6d6f38e7b3794f9257a86a0c</td></tr>
<tr><td>queue</td><td>sync_location</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retried_at</td><td>1443579632.4690034</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>1</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>3096ffd2-3cfd-4224-8750-4dfa860fc423</td></tr>
</table>
<h2>Backtrace</h2>
<pre>

</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 30",1]}' title='{"runtimeerror":["Sep 30",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Redis::CommandError occurred in </h2>
<pre>
OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.

</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-10-01 17:35:49 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[6]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>created_at</td><td>1443710390.1370409</td></tr>
<tr><td>enqueued_at</td><td>1443710390.137077</td></tr>
<tr><td>error_class</td><td>Redis::CommandError</td></tr>
<tr><td>error_message</td><td>OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.</td></tr>
<tr><td>failed_at</td><td>1443738919.1012526</td></tr>
<tr><td>jid</td><td>e9e127a6b4749479abf65e0e</td></tr>
<tr><td>queue</td><td>sync_location</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>fd98290d-4e96-4d44-a7a1-c671ef99fa2e</td></tr>
</table>
<h2>Backtrace</h2>
<pre>

</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=3&above-color=red&below-color=gray&width=5&limits=0,3&d=0,0,0,0,0,0,3' alt='{"runtimeerror":["Oct 01",3]}' title='{"runtimeerror":["Oct 01",3]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Redis::CommandError occurred in </h2>
<pre>
OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.
app/providers/steam_provider.rb:24:in `friends&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-10-17 19:02:34 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[1]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>created_at</td><td>1445126421.4274004</td></tr>
<tr><td>enqueued_at</td><td>1445126421.427448</td></tr>
<tr><td>error_class</td><td>Redis::CommandError</td></tr>
<tr><td>error_message</td><td>OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.</td></tr>
<tr><td>failed_at</td><td>1445126553.6756964</td></tr>
<tr><td>jid</td><td>1211d7f9f11f51051f16bebf</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>true</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>0e1ac7b0-eec3-4119-a8fd-f1730de2a4ed</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:24:in `friends&#39;
app/importers/steam_importer.rb:34:in `import_friends&#39;
lib/workers/sync_worker.rb:20:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Oct 18",1]}' title='{"runtimeerror":["Oct 18",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Redis::CommandError occurred in </h2>
<pre>
OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.
app/providers/steam_provider.rb:24:in `friends&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-10-22 19:03:33 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[1]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>created_at</td><td>1445558433.4493022</td></tr>
<tr><td>enqueued_at</td><td>1445558433.4493434</td></tr>
<tr><td>error_class</td><td>Redis::CommandError</td></tr>
<tr><td>error_message</td><td>OOM command not allowed when used memory &gt; &#39;maxmemory&#39;.</td></tr>
<tr><td>failed_at</td><td>1445558612.9597895</td></tr>
<tr><td>jid</td><td>54dcee59a3f30512fb576422</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>true</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>947c444a-148c-402c-9ca0-b63310ad26b3</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:24:in `friends&#39;
app/importers/steam_importer.rb:34:in `import_friends&#39;
lib/workers/sync_worker.rb:20:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Oct 23",1]}' title='{"runtimeerror":["Oct 23",1]}'/>
