### ISSUE TITLE
# (SteamCondenser::Error) "{\"br\"=>{}, \"__content__\"=>\"This user has not yet set up their Steam Community profile.If you know them, encourage him/her to set up their profile and join in on the gaming!\"}"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#285]
<meta name="exception_notification_http">
<h2>SteamCondenser::Error occurred in </h2>
<pre>
{&quot;br&quot;=&gt;{}, &quot;__content__&quot;=&gt;&quot;This user has not yet set up their Steam Community profile.If you know them, encourage him/her to set up their profile and join in on the gaming!&quot;}
app/importers/steam_importer.rb:67:in `create_user_from_friend&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-27 12:11:12 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[61]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1443272443.0992706</td></tr>
<tr><td>error_class</td><td>SteamCondenser::Error</td></tr>
<tr><td>error_message</td><td>{&quot;br&quot;=&gt;{}, &quot;__content__&quot;=&gt;&quot;This user has not yet set up their Steam Community profile.If you know them, encourage him/her to set up their profile and join in on the gaming!&quot;}</td></tr>
<tr><td>failed_at</td><td>1443272533.6596289</td></tr>
<tr><td>jid</td><td>8cd4140f0fcf1794f8fcf3c9</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retried_at</td><td>1443373872.4357748</td></tr>
<tr><td>retry</td><td>2</td></tr>
<tr><td>retry_count</td><td>2</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>e5f1a1b2-d131-48d9-ac3a-c572d1155222</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/importers/steam_importer.rb:67:in `create_user_from_friend&#39;
app/importers/steam_importer.rb:33:in `block in import_friends&#39;
app/importers/steam_importer.rb:32:in `each&#39;
app/importers/steam_importer.rb:32:in `import_friends&#39;
lib/workers/sync_worker.rb:19:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=2&above-color=red&below-color=gray&width=5&limits=0,2&d=0,0,0,0,0,0,2' alt='{"runtimeerror":["Sep 27",2]}' title='{"runtimeerror":["Sep 27",2]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>SteamCondenser::Error occurred in </h2>
<pre>
{&quot;br&quot;=&gt;{}, &quot;__content__&quot;=&gt;&quot;This user has not yet set up their Steam Community profile.If you know them, encourage him/her to set up their profile and join in on the gaming!&quot;}
app/providers/steam_provider.rb:13:in `initialize&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-10-21 18:59:57 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[59]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>created_at</td><td>1445471664.5916781</td></tr>
<tr><td>enqueued_at</td><td>1445471978.5498526</td></tr>
<tr><td>error_class</td><td>SteamCondenser::Error</td></tr>
<tr><td>error_message</td><td>{&quot;br&quot;=&gt;{}, &quot;__content__&quot;=&gt;&quot;This user has not yet set up their Steam Community profile.If you know them, encourage him/her to set up their profile and join in on the gaming!&quot;}</td></tr>
<tr><td>failed_at</td><td>1445471997.0720072</td></tr>
<tr><td>jid</td><td>0e65e11fe700600d51fb2711</td></tr>
<tr><td>queue</td><td>sync_location</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>194c9ed4-a28a-4fb3-963d-b4ab071aff64</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:13:in `initialize&#39;
lib/workers/location_sync_worker.rb:14:in `new&#39;
lib/workers/location_sync_worker.rb:14:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Oct 21",1]}' title='{"runtimeerror":["Oct 21",1]}'/>
