### ISSUE TITLE
# (Errno::ECONNREFUSED) "Connection refused - recvfrom({N})"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#286]
<meta name="exception_notification_http">
<h2>Errno::ECONNREFUSED occurred in </h2>
<pre>
Connection refused - recvfrom(2)
app/models/game_social_server.rb:41:in `block in server_info&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-27 14:00:05 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[117]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>enqueued_at</td><td>1443380067.5127916</td></tr>
<tr><td>error_class</td><td>Errno::ECONNREFUSED</td></tr>
<tr><td>error_message</td><td>Connection refused - recvfrom(2)</td></tr>
<tr><td>failed_at</td><td>1443380405.0572715</td></tr>
<tr><td>jid</td><td>888d3a12b0ddd6ef5fe6610f</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>b4f203a9-820c-411b-a541-8bd8bdc4ce61</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/models/game_social_server.rb:41:in `block in server_info&#39;
app/models/game_social_server.rb:38:in `server_info&#39;
app/models/game_social_server.rb:17:in `import_server&#39;
app/models/user.rb:148:in `set_game&#39;
app/importers/steam_importer.rb:96:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 27",1]}' title='{"runtimeerror":["Sep 27",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Errno::ECONNREFUSED occurred in </h2>
<pre>
Connection refused - recvfrom(2)
app/models/game_social_server.rb:41:in `block in server_info&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-27 23:11:03 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[250]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>created_at</td><td>1443413089.9333577</td></tr>
<tr><td>enqueued_at</td><td>1443413400.2782807</td></tr>
<tr><td>error_class</td><td>Errno::ECONNREFUSED</td></tr>
<tr><td>error_message</td><td>Connection refused - recvfrom(2)</td></tr>
<tr><td>failed_at</td><td>1443413463.1647975</td></tr>
<tr><td>jid</td><td>cbc48f6853c5866d189dbeb5</td></tr>
<tr><td>queue</td><td>sync_location</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>7dba4547-8d81-4f58-847f-93fa8a6d548a</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/models/game_social_server.rb:41:in `block in server_info&#39;
app/models/game_social_server.rb:38:in `server_info&#39;
app/models/game_social_server.rb:17:in `import_server&#39;
app/models/user.rb:145:in `set_game&#39;
app/importers/steam_importer.rb:100:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 28",1]}' title='{"runtimeerror":["Sep 28",1]}'/>
