### ISSUE TITLE
# (Redis::CommandError) "ERR max number of clients reached"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#287]
<meta name="exception_notification_http">
<h2>Redis::CommandError occurred in </h2>
<pre>
ERR max number of clients reached
lib/tasks/sync.rake:5:in `block (3 levels) in &lt;top (required)&gt;&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-27 15:44:21 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>action</td><td></td></tr>
<tr><td>component</td><td></td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>rake_env</td><td></td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>569c330c-37cb-4699-a67f-15d461cab7b8</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
lib/tasks/sync.rake:5:in `block (3 levels) in &lt;top (required)&gt;&#39;
lib/tasks/sync.rake:4:in `block (2 levels) in &lt;top (required)&gt;&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=297&above-color=red&below-color=gray&width=5&limits=0,297&d=0,0,0,0,0,0,297' alt='{"runtimeerror":["Oct 14",297]}' title='{"runtimeerror":["Oct 14",297]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Redis::CommandError occurred in </h2>
<pre>
ERR max number of clients reached
app/providers/steam_provider.rb:72:in `summary&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-28 19:49:42 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[11]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>created_at</td><td>1443487765.8252854</td></tr>
<tr><td>enqueued_at</td><td>1443487765.8253496</td></tr>
<tr><td>error_class</td><td>Redis::CommandError</td></tr>
<tr><td>error_message</td><td>ERR max number of clients reached</td></tr>
<tr><td>failed_at</td><td>1443487782.2601182</td></tr>
<tr><td>jid</td><td>5ded2700b5eb94ab8d6f21bd</td></tr>
<tr><td>queue</td><td>sync_location</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>88d94b9c-20a4-4ed0-8186-1c0ae83f10e4</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:72:in `summary&#39;
app/providers/steam_provider.rb:64:in `current_game&#39;
app/importers/steam_importer.rb:106:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=7&above-color=red&below-color=gray&width=5&limits=0,7&d=0,0,0,0,0,0,7' alt='{"runtimeerror":["Sep 29",7]}' title='{"runtimeerror":["Sep 29",7]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>Redis::CommandError occurred in </h2>
<pre>
ERR max number of clients reached
app/providers/steam_provider.rb:75:in `summary&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-10-14 16:49:46 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[20]</td></tr>
<tr><td>class</td><td>Workers::LocationSyncWorker</td></tr>
<tr><td>created_at</td><td>1444859376.44993</td></tr>
<tr><td>enqueued_at</td><td>1444859376.449972</td></tr>
<tr><td>error_class</td><td>Redis::CommandError</td></tr>
<tr><td>error_message</td><td>ERR max number of clients reached</td></tr>
<tr><td>failed_at</td><td>1444859386.1672704</td></tr>
<tr><td>jid</td><td>bbb81d4bd7db74601f8c890d</td></tr>
<tr><td>queue</td><td>sync_location</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>e6876cf4-1e6b-4a7c-a907-29b712184bcc</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:75:in `summary&#39;
app/providers/steam_provider.rb:67:in `current_game&#39;
app/importers/steam_importer.rb:114:in `import_location&#39;
lib/workers/location_sync_worker.rb:16:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=2&above-color=red&below-color=gray&width=5&limits=0,2&d=0,0,0,0,0,0,2' alt='{"runtimeerror":["Oct 14",2]}' title='{"runtimeerror":["Oct 14",2]}'/>
