### ISSUE TITLE
# (SteamCondenser::Error) "XML data could not be parsed: {N} Unknown"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#288]
<meta name="exception_notification_http">
<h2>SteamCondenser::Error occurred in </h2>
<pre>
XML data could not be parsed: 429 Unknown
app/providers/steam_provider.rb:38:in `block in group&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-27 20:23:01 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[11]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>created_at</td><td>1443403365.7186432</td></tr>
<tr><td>enqueued_at</td><td>1443403365.718678</td></tr>
<tr><td>error_class</td><td>SteamCondenser::Error</td></tr>
<tr><td>error_message</td><td>XML data could not be parsed: 429 Unknown</td></tr>
<tr><td>failed_at</td><td>1443403380.9160414</td></tr>
<tr><td>jid</td><td>5f4ef6068f2c7f9db6bb9212</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>3f4386a3-d53b-44f4-bcab-e7188fbb545f</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:38:in `block in group&#39;
app/providers/steam_provider.rb:37:in `group&#39;
app/providers/steam_provider.rb:32:in `block in groups&#39;
app/providers/steam_provider.rb:31:in `map&#39;
app/providers/steam_provider.rb:31:in `groups&#39;
app/importers/steam_importer.rb:49:in `import_groups&#39;
lib/workers/sync_worker.rb:18:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1316&above-color=red&below-color=gray&width=5&limits=0,1316&d=0,0,0,0,0,0,1316' alt='{"runtimeerror":["Sep 28",1316]}' title='{"runtimeerror":["Sep 28",1316]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>SteamCondenser::Error occurred in </h2>
<pre>
XML data could not be parsed: 429 Unknown
app/providers/steam_provider.rb:39:in `block in group&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-27 22:03:07 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[17]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>created_at</td><td>1443406969.8069682</td></tr>
<tr><td>enqueued_at</td><td>1443408612.5559409</td></tr>
<tr><td>error_class</td><td>SteamCondenser::Error</td></tr>
<tr><td>error_message</td><td>XML data could not be parsed: 429 Unknown</td></tr>
<tr><td>failed_at</td><td>1443407029.6150315</td></tr>
<tr><td>jid</td><td>001f704348f919b857ee6bd6</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retried_at</td><td>1443409387.0392675</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>3</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>61cbeb3e-af04-4bd5-9313-f75e5e18b8a3</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:39:in `block in group&#39;
app/providers/steam_provider.rb:38:in `group&#39;
app/providers/steam_provider.rb:32:in `block in groups&#39;
app/providers/steam_provider.rb:31:in `map&#39;
app/providers/steam_provider.rb:31:in `groups&#39;
app/importers/steam_importer.rb:49:in `import_groups&#39;
lib/workers/sync_worker.rb:18:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 28",1]}' title='{"runtimeerror":["Sep 28",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>SteamCondenser::Error occurred in </h2>
<pre>
XML data could not be parsed: 429 Unknown
app/providers/steam_provider.rb:39:in `block in group&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-27 22:03:24 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[46]</td></tr>
<tr><td>class</td><td>Workers::SyncWorker</td></tr>
<tr><td>created_at</td><td>1443406969.830077</td></tr>
<tr><td>enqueued_at</td><td>1443408612.6718264</td></tr>
<tr><td>error_class</td><td>SteamCondenser::Error</td></tr>
<tr><td>error_message</td><td>XML data could not be parsed: 429 Unknown</td></tr>
<tr><td>failed_at</td><td>1443407056.11652</td></tr>
<tr><td>jid</td><td>de60edaacd8815bc1f7943cc</td></tr>
<tr><td>queue</td><td>sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retried_at</td><td>1443409404.017096</td></tr>
<tr><td>retry</td><td>10</td></tr>
<tr><td>retry_count</td><td>3</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>61cbeb3e-af04-4bd5-9313-f75e5e18b8a3</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/providers/steam_provider.rb:39:in `block in group&#39;
app/providers/steam_provider.rb:38:in `group&#39;
app/providers/steam_provider.rb:32:in `block in groups&#39;
app/providers/steam_provider.rb:31:in `map&#39;
app/providers/steam_provider.rb:31:in `groups&#39;
app/importers/steam_importer.rb:49:in `import_groups&#39;
lib/workers/sync_worker.rb:18:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 28",1]}' title='{"runtimeerror":["Sep 28",1]}'/>
