### ISSUE TITLE
game_social_servers#show (Errno::EHOSTUNREACH) "No route to host - recvfrom({N})"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#293]
<meta name="exception_notification_http">
<h2>Errno::EHOSTUNREACH occurred in game_social_servers</h2>
<pre>
No route to host - recvfrom(2)
app/models/game_social_server.rb:41:in `block in server_info&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://social.cloud1001.co/game_social_servers/5</td></tr>
<tr><td>IP address</td><td>94.236.7.190</td></tr>
<tr><td>Parameters</td><td>{&quot;action&quot;=&gt;&quot;show&quot;, &quot;controller&quot;=&gt;&quot;game_social_servers&quot;, &quot;id&quot;=&gt;&quot;5&quot;}</td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-28 11:06:12 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td>&quot;a2815db2fa1085896c4445f13f1620b8&quot;</td></tr>
<tr><td>data</td><td>#&lt;ActionDispatch::Request::Session:0x007f9387057b08 ...&gt;
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>HTTP_ACCEPT</td><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr>
<tr><td>HTTP_ACCEPT_ENCODING</td><td>gzip, deflate, sdch</td></tr>
<tr><td>HTTP_ACCEPT_LANGUAGE</td><td>en-US,en;q=0.8</td></tr>
<tr><td>HTTP_CONNECTION</td><td>close</td></tr>
<tr><td>HTTP_COOKIE</td><td>remember_token=ca0iAChlPY59ZRYrnX6mbg; _GameSocial_session=bHUvUlpyYlNDVnp5eEFZZHVKUVplRU40YzdrbjJyNzgxbGREd3JhZ25lWkQvTkovZHBJY3BxaFNHRXpLTUpyV3NmZEVjZEpFem53aHFQcGk1VXQ1bC9jUk54MFVMbkgvZ01oMnVyVTRqTDd5YzFsbml4Qlg1S1lHbGpDM28vRHppTnRZTE1XcGZPNTYzTnB1VWVtd1UvTi9hcG1BR05Db0g0UkdndzdFaXF1TFdLeFZiWkU1Q0ZxY2tmQjRTWmp6aGFMTmhybmhJOEV1VUp6R0dIU3Q0QlY1RnVZZDFYNGJNS0hkeDRhcWppOGxJK3pueElIL3RlcmdxUTlTclFEUUoralFDN2pHNXN3YmowbktwK0thQXhzZURsWXVEcnoyL2ZUMjFXWFhlNUxjNHdteFV1ak1JSHdCdnJ1NSttU1U1dXcvWlJ5VU1qSlFiMXNYSXJydDI4R0hxMTd5THNSeCtwZEZqaGQwaXpVQjQ4WXUzejNxVm5VQW41SUNZRzk0LS1RcTZ0QWljZTEvUklicjZNZGpNOWN3PT0%3D--5dca2fecb2da9fc50371ae352be1934d3a096462</td></tr>
<tr><td>HTTP_DNT</td><td>1</td></tr>
<tr><td>HTTP_HOST</td><td>social.cloud1001.co</td></tr>
<tr><td>HTTP_UPGRADE_INSECURE_REQUESTS</td><td>1</td></tr>
<tr><td>HTTP_USER_AGENT</td><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36</td></tr>
<tr><td>HTTP_VERSION</td><td>HTTP/1.1</td></tr>
<tr><td>HTTP_VIA</td><td>1.1 542204-LON4WWSG01.secops.rackspace.com 0A02CC2D</td></tr>
<tr><td>HTTP_X_FORWARDED_FOR</td><td>94.236.7.190</td></tr>
<tr><td>HTTP_X_FORWARDED_PORT</td><td>80</td></tr>
<tr><td>HTTP_X_FORWARDED_PROTO</td><td>http</td></tr>
<tr><td>HTTP_X_REQUEST_ID</td><td>576bc79b-7777-46f5-b7f5-92bd4975724e</td></tr>
<tr><td>HTTP_X_REQUEST_START</td><td>1443456371519</td></tr>
<tr><td>ORIGINAL_FULLPATH</td><td>/game_social_servers/5</td></tr>
<tr><td>ORIGINAL_SCRIPT_NAME</td><td></td></tr>
<tr><td>PATH_INFO</td><td>/game_social_servers/5</td></tr>
<tr><td>QUERY_STRING</td><td></td></tr>
<tr><td>REMOTE_ADDR</td><td>10.168.190.187</td></tr>
<tr><td>REQUEST_METHOD</td><td>GET</td></tr>
<tr><td>REQUEST_PATH</td><td>/game_social_servers/5</td></tr>
<tr><td>REQUEST_URI</td><td>/game_social_servers/5</td></tr>
<tr><td>ROUTES_70135790690380_SCRIPT_NAME</td><td></td></tr>
<tr><td>SCRIPT_NAME</td><td></td></tr>
<tr><td>SERVER_NAME</td><td>social.cloud1001.co</td></tr>
<tr><td>SERVER_PORT</td><td>80</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>HTTP/1.1</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>Unicorn 4.8.3</td></tr>
<tr><td>action_controller.instance</td><td>game_social_servers#show</td></tr>
<tr><td>action_dispatch.backtrace_cleaner</td><td>#&lt;Rails::BacktraceCleaner:0x007f9387e9b1d8&gt;</td></tr>
<tr><td>action_dispatch.cookies</td><td>#&lt;ActionDispatch::Cookies::CookieJar:0x007f9385e98020&gt;</td></tr>
<tr><td>action_dispatch.cookies_serializer</td><td></td></tr>
<tr><td>action_dispatch.encrypted_cookie_salt</td><td>encrypted cookie</td></tr>
<tr><td>action_dispatch.encrypted_signed_cookie_salt</td><td>signed encrypted cookie</td></tr>
<tr><td>action_dispatch.http_auth_salt</td><td>http authentication</td></tr>
<tr><td>action_dispatch.key_generator</td><td>#&lt;ActiveSupport::CachingKeyGenerator:0x007f9387e9ab98&gt;</td></tr>
<tr><td>action_dispatch.logger</td><td>#&lt;Logger:0x007f9385b633c8&gt;</td></tr>
<tr><td>action_dispatch.parameter_filter</td><td>[:password]</td></tr>
<tr><td>action_dispatch.redirect_filter</td><td>[]</td></tr>
<tr><td>action_dispatch.remote_ip</td><td>94.236.7.190</td></tr>
<tr><td>action_dispatch.request.content_type</td><td></td></tr>
<tr><td>action_dispatch.request.formats</td><td>[#&lt;Mime::Type:0x007f938483fa58 @synonyms=[&quot;application/xhtml+xml&quot;], @symbol=:html, @string=&quot;text/html&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.parameters</td><td>{&quot;action&quot;=&gt;&quot;show&quot;, &quot;controller&quot;=&gt;&quot;game_social_servers&quot;, &quot;id&quot;=&gt;&quot;5&quot;}</td></tr>
<tr><td>action_dispatch.request.path_parameters</td><td>{:action=&gt;&quot;show&quot;, :controller=&gt;&quot;game_social_servers&quot;, :id=&gt;&quot;5&quot;}</td></tr>
<tr><td>action_dispatch.request.query_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.request_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.unsigned_session_cookie</td><td>{&quot;session_id&quot;=&gt;&quot;a2815db2fa1085896c4445f13f1620b8&quot;, &quot;_csrf_token&quot;=&gt;&quot;Jid+BSxZGxSPz6Xo9pqQbU3zYVZoJHLyuKL+C4UhCu0=&quot;, &quot;flash&quot;=&gt;{&quot;discard&quot;=&gt;[], &quot;flashes&quot;=&gt;{&quot;notice&quot;=&gt;&quot;Game server was successfully created.&quot;}}, &quot;return_to&quot;=&gt;&quot;http://social.cloud1001.co/users/248&quot;}</td></tr>
<tr><td>action_dispatch.request_id</td><td>576bc79b-7777-46f5-b7f5-92bd4975724e</td></tr>
<tr><td>action_dispatch.routes</td><td>#&lt;ActionDispatch::Routing::RouteSet:0x007f9385c7c098&gt;</td></tr>
<tr><td>action_dispatch.secret_key_base</td><td>01c2fcf30be73aa2250d7267fb2d907f1b9cfb47c44c0af798bdf884093f09c6ec1a5dafd7988fdd09f87b1827cc038714dec16299c8c1f318c51269554bd1ac</td></tr>
<tr><td>action_dispatch.secret_token</td><td></td></tr>
<tr><td>action_dispatch.show_detailed_exceptions</td><td>false</td></tr>
<tr><td>action_dispatch.show_exceptions</td><td>true</td></tr>
<tr><td>action_dispatch.signed_cookie_salt</td><td>signed cookie</td></tr>
<tr><td>rack.errors</td><td>#&lt;IO:0x007f9382ac1530&gt;</td></tr>
<tr><td>rack.hijack</td><td>#&lt;Proc:0x007f9387070c70@/app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_request.rb:111&gt;</td></tr>
<tr><td>rack.hijack?</td><td>true</td></tr>
<tr><td>rack.input</td><td>#&lt;StringIO:0x007f9383908af8&gt;</td></tr>
<tr><td>rack.logger</td><td>#&lt;Logger:0x007f938398eec8&gt;</td></tr>
<tr><td>rack.multiprocess</td><td>true</td></tr>
<tr><td>rack.multithread</td><td>false</td></tr>
<tr><td>rack.request.cookie_hash</td><td>{&quot;remember_token&quot;=&gt;&quot;ca0iAChlPY59ZRYrnX6mbg&quot;, &quot;_GameSocial_session&quot;=&gt;&quot;bHUvUlpyYlNDVnp5eEFZZHVKUVplRU40YzdrbjJyNzgxbGREd3JhZ25lWkQvTkovZHBJY3BxaFNHRXpLTUpyV3NmZEVjZEpFem53aHFQcGk1VXQ1bC9jUk54MFVMbkgvZ01oMnVyVTRqTDd5YzFsbml4Qlg1S1lHbGpDM28vRHppTnRZTE1XcGZPNTYzTnB1VWVtd1UvTi9hcG1BR05Db0g0UkdndzdFaXF1TFdLeFZiWkU1Q0ZxY2tmQjRTWmp6aGFMTmhybmhJOEV1VUp6R0dIU3Q0QlY1RnVZZDFYNGJNS0hkeDRhcWppOGxJK3pueElIL3RlcmdxUTlTclFEUUoralFDN2pHNXN3YmowbktwK0thQXhzZURsWXVEcnoyL2ZUMjFXWFhlNUxjNHdteFV1ak1JSHdCdnJ1NSttU1U1dXcvWlJ5VU1qSlFiMXNYSXJydDI4R0hxMTd5THNSeCtwZEZqaGQwaXpVQjQ4WXUzejNxVm5VQW41SUNZRzk0LS1RcTZ0QWljZTEvUklicjZNZGpNOWN3PT0=--5dca2fecb2da9fc50371ae352be1934d3a096462&quot;}</td></tr>
<tr><td>rack.request.cookie_string</td><td>remember_token=ca0iAChlPY59ZRYrnX6mbg; _GameSocial_session=bHUvUlpyYlNDVnp5eEFZZHVKUVplRU40YzdrbjJyNzgxbGREd3JhZ25lWkQvTkovZHBJY3BxaFNHRXpLTUpyV3NmZEVjZEpFem53aHFQcGk1VXQ1bC9jUk54MFVMbkgvZ01oMnVyVTRqTDd5YzFsbml4Qlg1S1lHbGpDM28vRHppTnRZTE1XcGZPNTYzTnB1VWVtd1UvTi9hcG1BR05Db0g0UkdndzdFaXF1TFdLeFZiWkU1Q0ZxY2tmQjRTWmp6aGFMTmhybmhJOEV1VUp6R0dIU3Q0QlY1RnVZZDFYNGJNS0hkeDRhcWppOGxJK3pueElIL3RlcmdxUTlTclFEUUoralFDN2pHNXN3YmowbktwK0thQXhzZURsWXVEcnoyL2ZUMjFXWFhlNUxjNHdteFV1ak1JSHdCdnJ1NSttU1U1dXcvWlJ5VU1qSlFiMXNYSXJydDI4R0hxMTd5THNSeCtwZEZqaGQwaXpVQjQ4WXUzejNxVm5VQW41SUNZRzk0LS1RcTZ0QWljZTEvUklicjZNZGpNOWN3PT0%3D--5dca2fecb2da9fc50371ae352be1934d3a096462</td></tr>
<tr><td>rack.request.query_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_string</td><td></td></tr>
<tr><td>rack.run_once</td><td>false</td></tr>
<tr><td>rack.session</td><td>#&lt;ActionDispatch::Request::Session:0x007f9387057b08&gt;</td></tr>
<tr><td>rack.session.options</td><td>#&lt;ActionDispatch::Request::Session::Options:0x007f9387057ab8&gt;</td></tr>
<tr><td>rack.url_scheme</td><td>http</td></tr>
<tr><td>rack.version</td><td>[1, 2]</td></tr>
<tr><td>Process</td><td>10</td></tr>
<tr><td>Server</td><td>5badd0e7-e612-4825-8d3c-d997cd473870</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
app/models/game_social_server.rb:41:in `block in server_info&#39;
app/models/game_social_server.rb:38:in `server_info&#39;
app/models/game_social_server.rb:17:in `import_server&#39;
app/controllers/game_social_servers_controller.rb:16:in `show&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 28",1]}' title='{"runtimeerror":["Sep 28",1]}'/>

**Comment by bfosberry** [comment]
Needs to be supressed
