### ISSUE TITLE
# (ArgumentError) "wrong number of arguments ({N} for {N}..{N})"

### ISSUE THREAD

**Issue by bfosberry** [bfosberry/GameSocial#294]
<meta name="exception_notification_http">
<h2>ArgumentError occurred in </h2>
<pre>
wrong number of arguments (1 for 2..3)
lib/workers/group_sync_worker.rb:10:in `perform&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-28 19:50:46 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[&quot;103582791439010664&quot;]</td></tr>
<tr><td>class</td><td>Workers::GroupSyncWorker</td></tr>
<tr><td>created_at</td><td>1443487769.5195725</td></tr>
<tr><td>enqueued_at</td><td>1443487769.5197182</td></tr>
<tr><td>error_class</td><td>ArgumentError</td></tr>
<tr><td>error_message</td><td>wrong number of arguments (1 for 2..3)</td></tr>
<tr><td>failed_at</td><td>1443487846.386244</td></tr>
<tr><td>jid</td><td>878d55277c1cce453bdf0039</td></tr>
<tr><td>queue</td><td>group_sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retry</td><td>true</td></tr>
<tr><td>retry_count</td><td>0</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>88d94b9c-20a4-4ed0-8186-1c0ae83f10e4</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
lib/workers/group_sync_worker.rb:10:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=129&above-color=red&below-color=gray&width=5&limits=0,129&d=129,0,0,0,0,0,65' alt='{"runtimeerror":["Oct 05",129,"Oct 11",65]}' title='{"runtimeerror":["Oct 05",129,"Oct 11",65]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>ArgumentError occurred in </h2>
<pre>
wrong number of arguments (1 for 2..3)
lib/workers/group_sync_worker.rb:10:in `perform&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-28 22:40:24 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[&quot;103582791435633447&quot;]</td></tr>
<tr><td>class</td><td>Workers::GroupSyncWorker</td></tr>
<tr><td>created_at</td><td>1443487836.743947</td></tr>
<tr><td>enqueued_at</td><td>1443498024.2216792</td></tr>
<tr><td>error_class</td><td>ArgumentError</td></tr>
<tr><td>error_message</td><td>wrong number of arguments (1 for 2..3)</td></tr>
<tr><td>failed_at</td><td>1443487851.903161</td></tr>
<tr><td>jid</td><td>942f35070531923f43eadf41</td></tr>
<tr><td>queue</td><td>group_sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retried_at</td><td>1443498024.228731</td></tr>
<tr><td>retry</td><td>true</td></tr>
<tr><td>retry_count</td><td>9</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>7787671f-3c6d-40be-a6d0-74324a7e6fea</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
lib/workers/group_sync_worker.rb:10:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 29",1]}' title='{"runtimeerror":["Sep 29",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>ArgumentError occurred in </h2>
<pre>
wrong number of arguments (1 for 2..3)
lib/workers/group_sync_worker.rb:10:in `perform&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-29 13:13:50 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[&quot;103582791435633447&quot;]</td></tr>
<tr><td>class</td><td>Workers::GroupSyncWorker</td></tr>
<tr><td>created_at</td><td>1443487836.743947</td></tr>
<tr><td>enqueued_at</td><td>1443550430.2811544</td></tr>
<tr><td>error_class</td><td>ArgumentError</td></tr>
<tr><td>error_message</td><td>wrong number of arguments (1 for 2..3)</td></tr>
<tr><td>failed_at</td><td>1443487851.903161</td></tr>
<tr><td>jid</td><td>942f35070531923f43eadf41</td></tr>
<tr><td>queue</td><td>group_sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retried_at</td><td>1443550430.5409963</td></tr>
<tr><td>retry</td><td>true</td></tr>
<tr><td>retry_count</td><td>13</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>7787671f-3c6d-40be-a6d0-74324a7e6fea</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
lib/workers/group_sync_worker.rb:10:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 29",1]}' title='{"runtimeerror":["Sep 29",1]}'/>

**Comment by bfosberry** [comment]
<meta name="exception_notification_http">
<h2>ArgumentError occurred in </h2>
<pre>
wrong number of arguments (1 for 2..3)
lib/workers/group_sync_worker.rb:10:in `perform&#39;
</pre>
<h2>Request</h2>
<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://:</td></tr>
<tr><td>IP address</td><td></td></tr>
<tr><td>Parameters</td><td></td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-09-29 21:34:22 -0500</td></tr>
</table>
<h2>Session</h2>
<table class="table table-hover table-condensed">
<tr><td>session id</td><td></td></tr>
<tr><td>data</td><td>{}
</td></tr>
</table>
<h2>Environment</h2>
<table class="table table-hover table-condensed">
<tr><td>args</td><td>[&quot;103582791432768194&quot;]</td></tr>
<tr><td>class</td><td>Workers::GroupSyncWorker</td></tr>
<tr><td>created_at</td><td>1443487856.8291907</td></tr>
<tr><td>enqueued_at</td><td>1443579539.8761182</td></tr>
<tr><td>error_class</td><td>ArgumentError</td></tr>
<tr><td>error_message</td><td>wrong number of arguments (1 for 2..3)</td></tr>
<tr><td>failed_at</td><td>1443487857.570635</td></tr>
<tr><td>jid</td><td>dc1314d94ee6a70270ffdd6d</td></tr>
<tr><td>queue</td><td>group_sync</td></tr>
<tr><td>rack.session</td><td>{}</td></tr>
<tr><td>retried_at</td><td>1443580462.2397838</td></tr>
<tr><td>retry</td><td>true</td></tr>
<tr><td>retry_count</td><td>14</td></tr>
<tr><td>Process</td><td>3</td></tr>
<tr><td>Server</td><td>1f669550-6453-45f2-8553-82a098d50f57</td></tr>
</table>
<h2>Backtrace</h2>
<pre>
lib/workers/group_sync_worker.rb:10:in `perform&#39;
</pre>
<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Sep 30",1]}' title='{"runtimeerror":["Sep 30",1]}'/>
